title: Ara Jo
logo: /assets/img/IMG_3603.JPG
description: "Associate Professor <br>Department of Economics<br>University of Bath"
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

orcid_url: https://orcid.org/0000-0001-6205-1768
scholar_url: https://scholar.google.ch/citations?user=mnmBKcAAAAAJ&hl=en
email: aj2306@bath.ac.uk
